-- 03_snapshot_view.sql
-- Core curated snapshot view (fact + dimensions)

USE DATABASE WHISKY_DWH;
USE SCHEMA CURATED;

CREATE OR REPLACE VIEW VW_PRODUCT_SNAPSHOT AS
SELECT
  -- Fact identifiers
  f.SNAPSHOT_KEY,
  d.FULL_DATE,

  -- Product attributes
  p.PRODUCT_ID,
  p.NAME,
  p.BRAND,
  p.CATEGORY,
  p.REGION,

  -- Flavor profile
  p.STYLE_BODY,
  p.STYLE_RICHNESS,
  p.STYLE_SMOKE,
  p.STYLE_SWEETNESS,
  p.CHARACTER_NOTES,

  -- Bottle / ABV / age attributes
  p.BOTTLE_SIZE_L,
  p.BOTTLE_SIZE_CL,
  p.BOTTLE_SIZE_BAND,
  p.IS_STANDARD_BOTTLE,
  p.IS_COMPARABLE_BOTTLE,
  p.ABV_PERCENT,
  p.ABV_BAND,
  p.IS_CASK_STRENGTH,
  p.AGE_YEARS,
  p.IS_AGE_STATED,
  p.AGE_BAND,

  -- Outlier flags
  p.IS_PRICE_OUTLIER,
  p.IS_VALUE_OUTLIER,
  p.IS_OUTLIER,

  -- Categorization
  pt.PRICE_TIER,
  db.DISCOUNT_BAND,

  -- Snapshot metrics
  f.PRICE_EX_VAT_GBP,
  f.PRICE_INC_VAT_GBP,
  f.PRICE_BEFORE_DISCOUNT_GBP,
  f.UNIT_PRICE_GBP_PER_LITRE,
  f.REFERENCE_PRICE_GBP,
  f.ALCOHOL_UNITS,
  f.PRICE_PER_ALCOHOL_UNIT_GBP,
  f.DISCOUNT_AMOUNT_GBP,
  f.IS_DISCOUNTED,
  f.DISCOUNT_PERCENT,
  f.RATING_STARS,
  f.REVIEW_COUNT
FROM FACT_PRODUCT_SNAPSHOT f
JOIN DIM_DATE d ON d.DATE_KEY = f.DATE_KEY
JOIN DIM_PRODUCT p ON p.PRODUCT_KEY = f.PRODUCT_KEY
LEFT JOIN DIM_PRICE_TIER pt ON pt.PRICE_TIER_KEY = f.PRICE_TIER_KEY
LEFT JOIN DIM_DISCOUNT_BAND db ON db.DISCOUNT_BAND_KEY = f.DISCOUNT_BAND_KEY;
